import { StyleSheet } from 'react-native';

import {
  colors,
  cardShadowElevated,
  cardShadowLight,
  glassBorder,
  inputFieldStyle,
  spacing,
  typography,
} from '../../constants/theme';

export const adminStyles = StyleSheet.create({
  scrollContent: {
    padding: spacing.screenHorizontal,
    paddingBottom: 40,
  },
  blockTitle: {
    ...typography.sectionTitle,
    marginBottom: 10,
  },
  sectionHint: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
    marginBottom: 16,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: spacing.cardRadiusLg,
    padding: 16,
    marginBottom: 24,
    ...glassBorder,
    ...cardShadowElevated,
  },
  /** Content styles for SurfaceCard-based admin section panels. */
  sectionCard: {
    padding: 16,
    marginBottom: 24,
  },
  field: {
    marginBottom: 14,
  },
  fieldLabel: {
    ...typography.label,
    marginBottom: 6,
  },
  input: {
    ...inputFieldStyle,
    fontSize: 15,
    color: colors.textPrimary,
    backgroundColor: colors.surface,
    ...cardShadowLight,
  },
  inputMultiline: {
    minHeight: 88,
    textAlignVertical: 'top',
  },
  primaryButton: {
    backgroundColor: colors.primary,
    flex: 1,
    borderRadius: spacing.buttonRadius,
    minHeight: 48,
  },
  primaryButtonText: {
    color: '#fff',
    fontWeight: '800',
  },
  secondaryButton: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: colors.primaryMuted,
    backgroundColor: colors.surface,
    borderRadius: spacing.buttonRadius,
    minHeight: 48,
  },
  secondaryButtonText: {
    color: colors.primary,
    fontWeight: '700',
  },
  sendLiveButton: {
    backgroundColor: colors.primaryLight,
    borderWidth: 1,
    borderColor: colors.primaryMuted,
    borderRadius: spacing.buttonRadius,
    paddingVertical: 12,
  },
  sendLiveButtonText: {
    color: colors.primary,
    fontWeight: '700',
    fontSize: 14,
  },
  sendLiveHint: {
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 4,
    lineHeight: 17,
    paddingHorizontal: 4,
  },
  listSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  listSectionHeaderAddOnly: {
    justifyContent: 'flex-end',
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  addButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
  loader: {
    marginVertical: 24,
  },
  emptyText: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
    textAlign: 'center',
    paddingVertical: 8,
  },
  listRowCard: {
    padding: 16,
    marginBottom: 12,
  },
  listRowTop: {
    flexDirection: 'row',
    gap: 8,
  },
  listRowFooter: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  listRowMeta: {
    flex: 1,
  },
  listRowTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  listRowSubtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 4,
  },
  listRowTag: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  listRowStatus: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 6,
  },
  draftBadge: {
    marginTop: 6,
    alignSelf: 'flex-start',
    fontSize: 11,
    fontWeight: '700',
    color: colors.accentOrange,
    backgroundColor: colors.warningLight,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: spacing.chipRadius,
    overflow: 'hidden',
  },
  listRowActions: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  iconButton: {
    padding: 6,
  },
  iconButtonDisabled: {
    opacity: 0.35,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  modalHeader: {
    paddingTop: 20,
    paddingHorizontal: spacing.screenHorizontal,
    paddingBottom: 16,
    backgroundColor: colors.surface,
    borderBottomLeftRadius: spacing.cardRadiusLg,
    borderBottomRightRadius: spacing.cardRadiusLg,
    ...glassBorder,
    ...cardShadowLight,
  },
  modalTitle: {
    ...typography.screenTitle,
    fontSize: 22,
  },
  formError: {
    ...typography.bodySecondary,
    color: colors.danger,
    marginTop: 8,
  },
  modalScroll: {
    paddingHorizontal: spacing.screenHorizontal,
    paddingTop: 16,
    paddingBottom: 16,
  },
  pdfPicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: colors.primaryMuted,
    borderRadius: spacing.inputRadius,
    padding: 14,
    backgroundColor: colors.primaryLight,
    marginBottom: 6,
  },
  pdfPickerText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.primary,
  },
  pdfHint: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 14,
  },
  pickImageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: spacing.chipRadius,
    borderWidth: 1,
    borderColor: colors.primaryMuted,
    backgroundColor: colors.primaryLight,
    marginBottom: 14,
  },
  pickImageText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
  },
  thumbnailPreview: {
    width: '100%',
    height: 120,
    borderRadius: spacing.inputRadius,
    marginBottom: 14,
    backgroundColor: colors.primaryMuted,
  },
  galleryScroll: {
    marginBottom: 14,
  },
  galleryScrollContent: {
    gap: 10,
    paddingVertical: 2,
  },
  galleryThumbWrap: {
    width: 88,
    height: 88,
    borderRadius: spacing.inputRadius,
    overflow: 'hidden',
    backgroundColor: colors.primaryMuted,
  },
  galleryThumb: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  galleryRemoveButton: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  galleryClearText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.danger,
    marginBottom: 14,
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  switchLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textPrimary,
    flex: 1,
    flexShrink: 1,
    paddingRight: 12,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: spacing.screenHorizontal,
    paddingVertical: 16,
    backgroundColor: colors.surface,
    borderTopLeftRadius: spacing.cardRadiusLg,
    borderTopRightRadius: spacing.cardRadiusLg,
    ...glassBorder,
    ...cardShadowElevated,
  },
  rowFields: {
    flexDirection: 'row',
    gap: 12,
  },
  halfField: {
    flex: 1,
  },
  listRowDateBlock: {
    alignSelf: 'flex-start',
    marginBottom: 8,
  },
  datePickerBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
  },
  datePickerBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
  },
  badgePreview: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: '600',
    color: colors.accentOrange,
  },
});
